name: CI Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test - Fast Unit Tests
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName~TokenOperationTests|FullyQualifiedName~TokenTypeTests|FullyQualifiedName~TemplateTests|FullyQualifiedName~YamlLoaderTests|FullyQualifiedName~ResourceLoaderTests|FullyQualifiedName~StringBuilderTests"

    - name: Test - InsertLinks Tests
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName~InsertLinksTests"

    - name: Test - Citation and Authority Tests
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName~CitationTests|FullyQualifiedName~AuthorityTests"

    - name: Test - Citator Tests (Sequential)
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName~CitatorTests"

    - name: Test - Real World Tests
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName~RealWorldTests" --collect:"XPlat Code Coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./tests/CiteUrl.Core.Tests/TestResults/*/coverage.cobertura.xml
